#!/opt/local/bin/bash
# Copyright (C) 2021 Luca Filipozzi

kdigCmd="/opt/local/bin/kdig"

valueExpected="82.195.75.110"
valueReceived=$(${kdigCmd} -4 @8.8.8.8 +short +tls-ca +tls-hostname=dns.google master.debian.org A 2>/dev/null)
if test $? -ne 0 ; then
  echo "ERR" # kdig failed
  exit 1
fi
if test "x${valueReceived}" == "x${valueExpected}" ; then
  echo "ACK" # dns-over-tls query success
else
  echo "NAK" # dns-over-tls query failure
fi
exit 0
